[namelist:jules_overbank]
compulsory=true
ns=namelist/JULES Science Settings/jules_overbank
sort-key=14
title=River overbank inundation options
url=https://metoffice.github.io/jules/latest/namelists/jules_rivers.nml.html#namelist-JULES_overbank

[namelist:jules_overbank=coef_b]
compulsory=true
description=Coefficient in the QBF (=bankfull discharge) allometry.
range=0:
sort-key=f
type=real
url=https://metoffice.github.io/jules/latest/namelists/jules_rivers.nml.html#JULES_overbank::coef_b

[namelist:jules_overbank=ent_ratio]
compulsory=true
description=Rosgen entrenchment ratio (= ratio of flood-prone width to bankfull width
           = of a channel, where flood-prone width = when the channel depth is
           = 2x bankfull depth)
range=0:
sort-key=g
type=real
url=https://metoffice.github.io/jules/latest/namelists/jules_rivers.nml.html#JULES_overbank::ent_ratio

[namelist:jules_overbank=exp_c]
compulsory=true
description=Exponent in the QBF (=bankfull discharge) allometry.
range=0:
sort-key=h
type=real
url=https://metoffice.github.io/jules/latest/namelists/jules_rivers.nml.html#JULES_overbank::exp_c

[namelist:jules_overbank=overbank_model]
compulsory=true
description=Choice of overbank inundation model
sort-key=a
trigger=namelist:jules_overbank=coef_b: 2;
       = namelist:jules_overbank=ent_ratio: 2;
       = namelist:jules_overbank=exp_c: 2;
       = namelist:jules_overbank=riv_a: 1, 2;
       = namelist:jules_overbank=riv_b: 1, 2;
       = namelist:jules_overbank=riv_c: 2, 3;
       = namelist:jules_overbank=riv_f: 2, 3;
url=https://metoffice.github.io/jules/latest/namelists/jules_rivers.nml.html#JULES_overbank::overbank_model
value-titles=Simple, Simple with Rosgen, Hypsometric integral
values=1,2,3
widget[rose-config-edit]=cylc8_compat.ComboBoxValueWidget

[namelist:jules_overbank=riv_a]
compulsory=true
description=Coefficient in the allometry for river width
range=0:
sort-key=d
type=real
url=https://metoffice.github.io/jules/latest/namelists/jules_rivers.nml.html#JULES_overbank::riv_a

[namelist:jules_overbank=riv_b]
compulsory=true
description=Exponent in the allometry for river width
range=0:
sort-key=e
type=real
url=https://metoffice.github.io/jules/latest/namelists/jules_rivers.nml.html#JULES_overbank::riv_b

[namelist:jules_overbank=riv_c]
compulsory=true
description=Coefficient in the allometry for river depth
range=0:
sort-key=b
type=real
url=https://metoffice.github.io/jules/latest/namelists/jules_rivers.nml.html#JULES_overbank::riv_c

[namelist:jules_overbank=riv_f]
compulsory=true
description=Exponent in the allometry for river depth
range=0:
sort-key=c
type=real
url=https://metoffice.github.io/jules/latest/namelists/jules_rivers.nml.html#JULES_overbank::riv_f
