[namelist:jules_deposition_species]
compulsory=true
description=Deposition parameters that depend on species
duplicate=true
ns=namelist/JULES Science Settings/jules_deposition/jules_deposition_species
title=Deposition Species
url=https://metoffice.github.io/jules/latest/namelists/jules_deposition.nml.html#namelist-JULES_DEPOSITION_SPECIES

[namelist:jules_deposition_species=dd_ice_coeff_io]
compulsory=true
description=Coefficients for quadratic dependency of dry deposition to ice
fail-if=any(this == -1073741824.0) ; # Invalid parameter value(s)
length=3
sort-key=6
type=real
url=https://metoffice.github.io/jules/latest/namelists/jules_deposition.nml.html#JULES_DEPOSITION_SPECIES::dd_ice_coeff_io

[namelist:jules_deposition_species=dep_species_name_io]
compulsory=true
description=Name of chemical species to be deposited
fail-if=(this == "'unset'") ; # Invalid name for deposited species
sort-key=01
trigger=namelist:jules_deposition_species=dd_ice_coeff_io: this == "'SO2'" or this == "'HNO3'" or this == "'HONO2'" or this == "'ISON'" or this == "'HCl'" or this == "'HOCl'" or this == "'HBr'" or this == "'HOBr'" ;
       =namelist:jules_deposition_species=diffusion_corr_io: this == "'NO2'" or this == "'O3'" or this == "'SO2'" or this == "'NH3'" or this == "'PAN'" or this == "'MPAN'" or this == "'PPAN'" or this == "'ONITU'" ;
       =namelist:jules_deposition_species=r_tundra_io: this == "'NO2'" or this == "'O3'" or this == "'CO'" or this == "'H2'" or this == "'PAN'" or this == "'MPAN'" or this == "'PPAN'" or this == "'ONITU'" ;
type=character
url=https://metoffice.github.io/jules/latest/namelists/jules_deposition.nml.html#JULES_DEPOSITION_SPECIES::dep_species_name_io

[namelist:jules_deposition_species=dep_species_rmm_io]
compulsory=true
description=Relative molecular mass (g mol-1), used in calculation of quasi-laminar resistance (Rb)
range=0:
sort-key=02a
type=real
url=https://metoffice.github.io/jules/latest/namelists/jules_deposition.nml.html#JULES_DEPOSITION_SPECIES::dep_species_rmm_io

[namelist:jules_deposition_species=diffusion_coeff_io]
compulsory=true
description=Diffusion coefficient (m2 s-1), used in calculation of quasi-laminar resistance (Rb)
range=-1,0:
sort-key=02b
type=real
url=https://metoffice.github.io/jules/latest/namelists/jules_deposition.nml.html#JULES_DEPOSITION_SPECIES::diffusion_coeff_io

[namelist:jules_deposition_species=diffusion_corr_io]
compulsory=true
description=Diffusion correction for stomatal conductance
range=0:
sort-key=04
type=real
url=https://metoffice.github.io/jules/latest/namelists/jules_deposition.nml.html#JULES_DEPOSITION_SPECIES::diffusion_corr_io

[namelist:jules_deposition_species=r_tundra_io]
compulsory=true
description=Surface resistance used in tundra region (s m-1)
range=0:1.0e+30
sort-key=05
type=real
url=https://metoffice.github.io/jules/latest/namelists/jules_deposition.nml.html#JULES_DEPOSITION_SPECIES::r_tundra_io

[namelist:jules_deposition_species=rsurf_std_io]
compulsory=true
description=Standard values of surface resistance (s m-1)
fail-if=len(this) != (namelist:jules_surface_types=npft)+(namelist:jules_surface_types=nnvg)
length=:
range=0:1.0e+30
sort-key=03
type=real
url=https://metoffice.github.io/jules/latest/namelists/jules_deposition.nml.html#JULES_DEPOSITION_SPECIES::rsurf_std_io
