[namelist:jules_deposition_species_specific]
compulsory=true
description=Deposition parameters that depend on species
ns=namelist/JULES Science Settings/jules_deposition/jules_deposition_species_specific
title=Deposition Species Specific
url=https://metoffice.github.io/jules/latest/namelists/jules_deposition.nml.html#namelist-JULES_DEPOSITION_SPECIES

[namelist:jules_deposition_species_specific=ch4_mml_io]
compulsory=true
description=Factor to convert methane flux to dry dep velocity
range=0:
sort-key=02b
type=real
url=https://metoffice.github.io/jules/latest/namelists/jules_deposition.nml.html#JULES_DEPOSITION_SPECIES::ch4_mml_io

[namelist:jules_deposition_species_specific=ch4_scaling_io]
compulsory=true
description=Scaling applied to CH4 soil uptake
range=0:
sort-key=02a
type=real
url=https://metoffice.github.io/jules/latest/namelists/jules_deposition.nml.html#JULES_DEPOSITION_SPECIES::ch4_scaling_io

[namelist:jules_deposition_species_specific=ch4_up_flux_io]
compulsory=true
description=Uptake of methane to different surface types
fail-if=len(this) != (namelist:jules_surface_types=npft)+(namelist:jules_surface_types=nnvg)
length=:
range=0:
sort-key=02c
type=real
url=https://metoffice.github.io/jules/latest/namelists/jules_deposition.nml.html#JULES_DEPOSITION_SPECIES::ch4_up_flux_io

[namelist:jules_deposition_species_specific=ch4dd_tundra_io]
compulsory=true
description=Coefficients of cubic fit for CH4 loss to tundra
fail-if=any(this == -1073741824.0) ; # Invalid parameter value(s)
length=4
sort-key=02d
type=real
url=https://metoffice.github.io/jules/latest/namelists/jules_deposition.nml.html#JULES_DEPOSITION_SPECIES::ch4dd_tundra_io

[namelist:jules_deposition_species_specific=cuticle_o3_io]
compulsory=true
description=Constant in calculation of cuticular resistance for ozone (s m-1)
range=0:1.0e+30
sort-key=1a
type=real
url=https://metoffice.github.io/jules/latest/namelists/jules_deposition.nml.html#JULES_DEPOSITION_SPECIES::cuticle_o3_io

[namelist:jules_deposition_species_specific=h2dd_c_io]
compulsory=true
description=Constant in quadratic function for hydrogen deposition
fail-if=len(this) != (namelist:jules_surface_types=npft)+(namelist:jules_surface_types=nnvg)
       =any(this == -1073741824.0) ; # Invalid parameter value(s)
length=:
sort-key=03a
type=real
url=https://metoffice.github.io/jules/latest/namelists/jules_deposition.nml.html#JULES_DEPOSITION_SPECIES::h2dd_c_io

[namelist:jules_deposition_species_specific=h2dd_m_io]
compulsory=true
description=Coefficient of first order term in quadratic function for hydrogen deposition
fail-if=len(this) != (namelist:jules_surface_types=npft)+(namelist:jules_surface_types=nnvg)
       =any(this == -1073741824.0) ; # Invalid parameter value(s)
length=:
sort-key=03b
type=real
url=https://metoffice.github.io/jules/latest/namelists/jules_deposition.nml.html#JULES_DEPOSITION_SPECIES::h2dd_m_io

[namelist:jules_deposition_species_specific=h2dd_q_io]
compulsory=true
description=Coefficient of second order term in quadratic function for hydrogen deposition
fail-if=len(this) != (namelist:jules_surface_types=npft)+(namelist:jules_surface_types=nnvg)
       =any(this == -1073741824.0) ; # Invalid parameter value(s)
length=:
sort-key=03c
type=real
url=https://metoffice.github.io/jules/latest/namelists/jules_deposition.nml.html#JULES_DEPOSITION_SPECIES::h2dd_q_io

[namelist:jules_deposition_species_specific=r_wet_soil_o3_io]
compulsory=true
description=Wet soil surface resistance for ozone (s m-1)
range=0:1.0e+30
sort-key=01b
type=real
url=https://metoffice.github.io/jules/latest/namelists/jules_deposition.nml.html#JULES_DEPOSITION_SPECIES::r_wet_soil_o3_io
